version: "3"
services:
  pterodactyl-exporter:
    # TODO: Change image name once it is released on Docker Hub
    image: LOENS2/pterodactyl-exporter:latest
    container_name: pterodactyl-exporter
    ports:
      - "9531:9531"
    volumes:
      - ../config.yml:/opt/pterodactyl_exporter/config/config.yml
